# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9965e180185de08f2baa36c7ab942191b3674a65e90d7f6c42652a4050730cd7119898c768e9f7a3bb0f7d50e2a0371ea5f4932f460329b9fbdc8f279c8de654

test:
  secret_key_base: 98b82cec8df576d2b9da4928d1b72fe0e658319012845b8e6314a480c669d31d6c0b2296ab5a1be704ec7654d7325d093d67e51851d401276f3c4a76ffdd5492

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
